export const cardTokens = {
  global: {
    width: '168px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    gap: '12px',
    gapBetweenCards: '12px',
    contentGap: '6px',
    imageSize: '148px',
    titleSize: '14px',
    titleLineHeight: '20px',
    metaSize: '12px',
    metaLineHeight: '17px',
    actionHeight: '34px',
    actionRadius: '8px',
    borderWidth: '1px',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gapBetweenSections: '24px',
    sectionHeaderBottomMargin: '12px',
    horizontalScrollPadding: '16px',
    desktopHorizontalPadding: '24px',
  },
  track: {
    width: '168px',
    cardHeight: '272px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    height: '72px',
    artworkSize: '56px',
    titleSize: '14px',
    titleLineHeight: '20px',
    artistSize: '12px',
    artistLineHeight: '17px',
    actionIconSize: '20px',
  },
  nftTrack: {
    width: '168px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    cardHeight: '298px',
    padding: '10px',
    bottomMetadataHeight: '95px',
    mintButtonHeight: '34px',
    titleSize: '14px',
    titleLineHeight: '20px',
    metaSize: '12px',
    metaLineHeight: '17px',
  },
  nft: {
    width: '168px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    imageSize: '148px',
    titleSize: '14px',
    titleLineHeight: '20px',
    metaSize: '12px',
    metaLineHeight: '17px',
    actionHeight: '34px',
    actionRadius: '8px',
  },
  artist: {
    width: '130px',
    avatarSize: '96px',
    nameSize: '14px',
    followersSize: '12px',
    followButtonHeight: '32px',
  },
  user: {
    width: '110px',
    avatarSize: '72px',
    usernameSize: '13px',
    verifiedBadgeSize: '16px',
  },
  playlist: {
    width: '168px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    titleSize: '14px',
    titleLineHeight: '20px',
    descriptionSize: '12px',
    descriptionLineHeight: '17px',
  },
  collection: {
    width: '168px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    titleSize: '14px',
    titleLineHeight: '20px',
    metaSize: '12px',
    metaLineHeight: '17px',
    actionHeight: '34px',
  },
  album: {
    width: '168px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    titleSize: '14px',
    titleLineHeight: '20px',
    artistSize: '12px',
    artistLineHeight: '17px',
  },
  mission: {
    height: '90px',
    padding: '16px',
    rewardIconSize: '40px',
    buttonHeight: '36px',
    progressBarHeight: '6px',
  },
  marketplace: {
    width: '168px',
    artworkWidth: '148px',
    artworkHeight: '148px',
    borderRadius: '12px',
    imageRadius: '10px',
    padding: '10px',
    badgePosition: 'Top Right',
    metadataHeight: '70px',
    buyButtonHeight: '34px',
  },
  feed: {
    padding: '16px',
    avatarSize: '44px',
    mediaRadius: '10px',
    actionButtonSize: '20px',
  },
  homeBanner: {
    height: '180px',
    borderRadius: '16px',
    padding: '20px',
    ctaButtonHeight: '40px',
  },
  section: {
    topMargin: '24px',
    bottomMargin: '24px',
    headerPadding: '0 16px',
  },
  animation: {
    hoverScale: 1.02,
    tapScale: 0.98,
    cardFade: '150ms',
    sectionReveal: '200ms',
  },
};
