export const cardTokens = {
  global: {
    borderRadius: '6px',
    padding: '12px',
    gapBetweenCards: '12px',
    gapBetweenSections: '24px',
    sectionHeaderBottomMargin: '12px',
    horizontalScrollPadding: '16px',
    desktopHorizontalPadding: '24px',
  },
  track: {
    width: '155px',
    cardHeight: '260px',
    artworkWidth: '155px',
    artworkHeight: '155px',
    height: '72px',
    artworkSize: '56px',
    titleSize: '12px',
    artistSize: '10px',
    actionIconSize: '20px',
    padding: '8px',
  },
  nftTrack: {
    width: '155px',
    artworkWidth: '155px',
    artworkHeight: '155px',
    cardHeight: '260px',
    padding: '8px',
    bottomMetadataHeight: '95px',
    mintButtonHeight: '28px',
  },
  artist: {
    width: '120px',
    avatarSize: '88px',
    nameSize: '14px',
    followersSize: '12px',
    followButtonHeight: '32px',
  },
  user: {
    width: '110px',
    avatarSize: '72px',
    usernameSize: '13px',
    verifiedBadgeSize: '16px',
  },
  playlist: {
    width: '165px',
    artworkWidth: '165px',
    artworkHeight: '165px',
    titleSize: '14px',
    descriptionSize: '12px',
  },
  album: {
    width: '165px',
    artworkWidth: '165px',
    artworkHeight: '165px',
    titleSize: '14px',
    artistSize: '12px',
  },
  mission: {
    height: '90px',
    padding: '16px',
    rewardIconSize: '40px',
    buttonHeight: '36px',
    progressBarHeight: '6px',
  },
  marketplace: {
    width: '175px',
    artworkWidth: '175px',
    artworkHeight: '175px',
    badgePosition: 'Top Right',
    metadataHeight: '70px',
    buyButtonHeight: '36px',
  },
  feed: {
    padding: '16px',
    avatarSize: '44px',
    mediaRadius: '10px',
    actionButtonSize: '20px',
  },
  homeBanner: {
    height: '180px',
    borderRadius: '16px',
    padding: '20px',
    ctaButtonHeight: '40px',
  },
  section: {
    topMargin: '24px',
    bottomMargin: '24px',
    headerPadding: '0 16px',
  },
  animation: {
    hoverScale: 1.02,
    tapScale: 0.98,
    cardFade: '150ms',
    sectionReveal: '200ms',
  },
};
