import { 
  Play, 
  Pause, 
  SkipForward, 
  SkipBack, 
  Music, 
  Volume2, 
  Search, 
  Heart, 
  MessageSquare, 
  Share2, 
  Award, 
  User, 
  Bell, 
  ShieldCheck, 
  Wallet, 
  Plus, 
  Trash, 
  Settings, 
  Sparkles, 
  TrendingUp, 
  Grid, 
  List,
  Info,
  ExternalLink,
  ChevronRight,
  Clock,
  History
} from 'lucide-react';

export const icons = {
  play: Play,
  pause: Pause,
  skipForward: SkipForward,
  skipBack: SkipBack,
  music: Music,
  volume: Volume2,
  search: Search,
  heart: Heart,
  comment: MessageSquare,
  share: Share2,
  award: Award,
  user: User,
  bell: Bell,
  verified: ShieldCheck,
  wallet: Wallet,
  plus: Plus,
  trash: Trash,
  settings: Settings,
  sparkles: Sparkles,
  trending: TrendingUp,
  grid: Grid,
  list: List,
  info: Info,
  externalLink: ExternalLink,
  chevronRight: ChevronRight,
  clock: Clock,
  history: History,
};
