import * as React from 'react';
import HorizontalScroll from '@/components/HorizontalScroll';
import { motion } from 'motion/react';
import { Sparkles, Zap, Music, Globe, Database, Cpu } from 'lucide-react';

export default function HorizontalCanvas() {
  const items = [
    {
      id: "ethereal-1",
      title: "Neural Synthesizer",
      subtitle: "Experimental Lab",
      description: "Real-time AI-powered sound synthesis generated by neural nodes on the TON network.",
      color: "#3b82f6",
      image: "https://ik.imagekit.io/aitoolkit/horizontal-scroll/synths.jpg?tr=w-800"
    },
    {
      id: "ethereal-2",
      title: "Audio Artifacts",
      subtitle: "NFT Collection",
      description: "Rare sonic imprints preserved as immutable data structures for true ownership and provenance.",
      color: "#8b5cf6",
      image: "https://ik.imagekit.io/aitoolkit/horizontal-scroll/artifacts.jpg?tr=w-800"
    },
    {
      id: "ethereal-3",
      title: "Decentralized Nodes",
      subtitle: "Network Infrastructure",
      description: "High-performance relay nodes providing sub-millisecond latency for global streaming.",
      color: "#10b981",
      image: "https://ik.imagekit.io/aitoolkit/horizontal-scroll/nodes.jpg?tr=w-800"
    }
  ];

  return (
    <div className="bg-neutral-900 min-h-screen">
      {/* Intro Hero Section */}
      <section className="h-screen flex flex-col justify-center items-center text-center px-6 relative overflow-hidden bg-black">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_-20%,rgba(59,130,246,0.15),transparent)]" />
        <motion.div
           initial={{ opacity: 0, y: 30 }}
           animate={{ opacity: 1, y: 0 }}
           transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
           className="relative z-10 space-y-6"
        >
          <div className="flex justify-center mb-6">
            <div className="w-16 h-16 rounded-2xl bg-blue-500/10 flex items-center justify-center border border-blue-500/20">
              <Sparkles className="w-8 h-8 text-blue-500 animate-pulse" />
            </div>
          </div>
          <h1 className="text-6xl md:text-8xl font-black uppercase tracking-tighter text-white">
            Sonic<br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">Voyager</span>
          </h1>
          <p className="text-xl text-neutral-400 max-w-xl mx-auto font-medium">
            Experience the smooth, high-fidelity horizontal landscape powered by Lenis and Framer Motion.
          </p>
          <div className="pt-8">
            <div className="flex flex-col items-center gap-2 text-neutral-500 font-mono text-xs uppercase tracking-widest">
              <span>Scroll Down</span>
              <motion.div 
                animate={{ y: [0, 8, 0] }}
                transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                className="w-px h-12 bg-gradient-to-b from-blue-500 to-transparent"
              />
            </div>
          </div>
        </motion.div>
      </section>

      {/* The Horizontal Scroll Component */}
      <HorizontalScroll items={items} />

      {/* Final Section */}
      <section className="h-[50vh] flex items-center justify-center bg-black border-t border-white/5">
        <div className="text-center space-y-8">
           <h2 className="text-4xl font-black uppercase tracking-tight text-white">Continue the Journey</h2>
           <div className="flex gap-4">
              {[Zap, Globe, Database, Cpu].map((Icon, i) => (
                <div key={i} className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center border border-white/10 hover:border-blue-500/50 transition-colors group">
                  <Icon className="w-5 h-5 text-neutral-500 group-hover:text-blue-400 transition-colors" />
                </div>
              ))}
           </div>
           <p className="text-neutral-500 font-mono text-[10px] uppercase tracking-widest">
             © 2026 TONJAM PROTOCOLS
           </p>
        </div>
      </section>
    </div>
  );
}
